spring:
  application:
     name : Spring-boot-with-mango-db

  data:
    mongodb:
      authentication-database : admin
      username : myAdminUser
      password : mySecurePassword
      database : demo
      port : 27017
      host : localhost
      auto-index-creation : true


---
spring.config.activate.on-profile: dev
spring:
   application:
     name : Spring-boot-with-mango-db-dev